title: inkdroid 
email: ehs@pobox.com
description: Paper or Plastic 
baseurl: ""
url: "https://inkdroid.org"
twitter_username: edsu
github_username: edsu
permalink: pretty
paginate: 10 
paginate_path: "/page/:num/"

tag_page_layout: tag
tag_page_dir: tag
tag_permalink_style: pretty

sass:
  sass_dir: _sass

exclude:
  - sync.sh
  - inkdroid.wordpress.2015-08-31.xml
  - .git

keep_files:
  - .dat
  - dat.json

include:
  - .well-known
  - .htaccess

plugins:
  - jekyll-compose
  - jekyll/tagging
  - jekyll-pandoc

markdown: 'Pandoc'

pandoc:
  extensions:
    - mathjax
    - csl: _styles/apa.csl
    - bibliography: citations.bib
    - metadata link-citations:true
