# Site settings
title: inkdroid 
email: ehs@pobox.com
description: Paper or Plastic 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://inkdroid.org" # the base hostname & protocol for your site
twitter_username: edsu
github_username: edsu
permalink: pretty

tag_page_layout: tag
tag_page_dir: tag
tag_permalink_style: pretty

# Build settings
sass:
  sass_dir: _sass

exclude:
  - sync.sh
  - inkdroid.wordpress.2015-08-31.xml

include:
  - .well-known
  - .htaccess

gems:
  - jekyll-compose
  - jekyll/tagging
  - jekyll-pandoc

markdown: pandoc
mardown_ext: markdown,mkdown,mkdwn,mkd,md,Rmd,rmd

pandoc:
  extensions:
    - smart
    - mathjax
    - csl: _styles/apa.csl
    - bibliography: citations.bib

