# Site settings
title: inkdroid 
email: ehs@pobox.com
description: Paper or Plastic 
baseurl: ""
url: "http://inkdroid.org"
twitter_username: edsu
github_username: edsu
permalink: pretty
paginate: 50 
paginate_path: "/page/:num/"

tag_page_layout: tag
tag_page_dir: tag
tag_permalink_style: pretty

# Build settings
sass:
  sass_dir: _sass

exclude:
  - sync.sh
  - inkdroid.wordpress.2015-08-31.xml

include:
  - .well-known
  - .htaccess

gems:
  - jekyll-compose
  - jekyll/tagging
  - jekyll-pandoc

markdown: 'pandoc'

pandoc:
  extensions:
    - smart
    - mathjax
    - csl: _styles/apa.csl
    - bibliography: citations.bib
    - metadata link-citations:true
